name: 'Setting env ${CI_COMMIT_BRANCH} up'
description: 'Set env variable ${CI_COMMIT_BRANCH}'
runs:
  using: "composite"
  steps: 
    - name: Extract branch name 
      id: extract-branch-name
      run: |
        echo "##[set-env name=CI_COMMIT_BRANCH;]$(echo ${GITHUB_REF#refs/heads/})"
        echo $(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')
      shell: bash