outputs:
  enabled: # id of the output
    description: 'say whether the branch is valid or not in order to apply sematic version'
    value: ${{ steps.variables.outputs.enabled }}
runs:
  using: "composite"
  steps: 
    - id: variables
      shell: bash
      run: |
        BRANCH_NAME=${GITHUB_REF##*/}
        if [[ $BRANCH_NAME =~ ^(master|beta)$ ]]; then
        echo "::set-output name=enabled::true"
        fi