name: 'Semanti Release'
description: 'Automates package release: detrmining the next version number'
inputs: 
  gh-token: 
    description: token git hub
    required: true
runs:
  using: "composite"
  steps:
    - name: semantic release 
      id: semantic-release
      shell: bash
      env: 
        GITHUB_TOKEN: ${{ inputs.gh-token }}
      run: echo coincide ${{steps.check-branch.outputs.match}}
        # - name: Semantic release
#         env:
#           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
#         run: npx semantic-release