name: 'Semanti Release'
description: 'Greet someone'
runs:
  using: "composite"
  env: 
    GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  steps: 
    - name: semantic release 
      id: semantic-release
      shell: bash
      run: echo $GITHUB_TOKEN ${GITHUB_REF##*/}    
# - name: Semantic release
#         env:
#           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
#         run: npx semantic-release