name: 'Semanti Release'
description: 'Crea los tags correspondientes (SemVer)'
inputs: 
  gh-token: 
    description: token git hub
    required: true
runs:
  using: "composite"
  steps: 
    - name: check branch
      id: check-branch
      shell: bash
      run: |
        if [[ ${GITHUB_REF##*/} =~ ^((development)|(hotfix.*))$ ]]; then
        echo ::set-output name=match::true
        fi
    - name: semantic release 
      id: semantic-release
      shell: bash
      env: 
        GITHUB_TOKEN: ${{ inputs.gh-token }}
      run: echo coincide ${{steps.check-branch.outputs.match}}
# - name: Semantic release
#         env:
#           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
#         run: npx semantic-release