name: 'Semanti Release'
description: 'Greet someone'
inputs: 
  gh-token: 
    description: token git hub
    required: true
runs:
  using: "composite"
  steps: 
    - name: semantic release 
      id: semantic-release
      shell: bash
      env: 
        GITHUB_TOKEN: ${{ inputs.gh-token }}
      run: echo $GITHUB_TOKEN ${GITHUB_REF##*/}
# - name: Semantic release
#         env:
#           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
#         run: npx semantic-release